# 터미널에서 자주 쓰이는 명령어 몇가지를 한글로 지정해주었습니다.
# Debian ,Ubuntu(Relatives), elementary OS 는  ~/.bash_aliases 로 저장하시구요,
# Linux Mint 는 ~/.bashrc 로 저장하세요.
# 기본 문서도구로 gedit 를 지정했습니다. 사용하시는 도구로 바꿔쓰세요.
# Debian 은 마지막의 sudo shutdown -P 를 sudo shutdown -hP 로 이용합니다.
alias update='sudo apt-get update'
# alias install='sudo apt-get install -y'
alias remove='sudo apt-get remove -y'
alias purge='sudo apt-get purge -y'
alias upgrade='sudo apt-get upgrade -y'
alias dist-upgrade='sudo apt-get dist-upgrade -y'
alias autoremove='sudo apt-get autoremove -y'
alias autoclean='sudo apt-get autoclean '
alias clean='sudo apt-get clean'
alias search='sudo apt-cache search'
# alias sg='sudo gedit'
alias ren='sudo mv -rf'
alias move='sudo mv -rf'
alias del='sudo rm -rf'
alias copy='sudo cp -rf'
alias app='sudo add-apt-repository -y'
alias app-r='sudo add-apt-repository --remove -y'
alias reboot='sudo reboot'
alias 다시='sudo reboot'
alias 이동='cd'
alias 보기='ls'
alias 이사='mv'
alias 이사-='sudo mv'
alias 복사='cp'
alias 복사-='sudo cp -rf'
alias 지움='rm'
alias 지움-='sudo rm -rf'
alias 이름='mv'
alias 이름-='sudo mv'
alias 압축='tar -zcvpf'
alias 압축-='tar -cvpf'
alias 풀기='sudo tar -zxvpf'
alias 풀기-='sudo tar -xvpf'
alias 찾기='sudo apt-cache search'
alias 제거='sudo apt-get remove --purge -y'
alias 설치='sudo apt-get install -y' 
alias 설치-='sudo dpkg -i *.deb'
alias 업뎃='sudo apt-get update'
alias 업글='sudo apt-get update; sudo apt-get upgrade -y'
alias 업그리='sudo apt-get update; sudo apt-get dist-upgrade -y'
alias 추가='sudo add-apt-repository -y'
alias 추가-='sudo add-apt-repository --remove -y'
alias 수지='sudo gedit'
alias 닫기='exit'
alias 청소='clear'
alias burg='sudo gedit /boot/burg/burg.cfg'
alias BURG='sudo gedit /boot/burg/burg.cfg'
alias grub='sudo gedit /boot/grub/grub.cfg'
alias GRUB='sudo gedit /boot/grub/grub.cfg'
alias 끔='sudo shutdown -P'
# 끔 다음에는 한 칸 띄고 숫자를 입력합니다. 숫자는 분을 의미 합니다. 지금 바로 끌때는 0 입니다.
